WindowManager:
    MainWindow:
    ContentWindow:
<P>:
    Label:
        text: "You Need To Complete Previous Lessons to Study this one."
        size_hint: 0.6, 0.2
        pos_hint: {"x":0.2, "top":1}

    Button:
        text: "Previous"
        size_hint: 0.8, 0.2
        pos_hint: {"x":0.1, "y":0.1}
<MainWindow>:
    name: "main"

    GridLayout:
        cols:1
        size: root.width , root.height



        GridLayout:
            rows: 2

            Label:
                text: "!! Welcome to Python Tutorial!!"
                font_size:40
                background_color: (1.0, 1.0, 0.0, 0.5)
            Label:
                text:"!!HAPPY LEARNING!!"

        Button:
            text: "NEXT"
            background_color: (1.0, 1.0, 1.0, 1.0)
            on_release:
                app.root.current = "content"
                root.manager.transition.direction = "left"


<ContentWindow>:
    name: "content"

    GridLayout:
        rows : 6

        Button:
            text: "Lesson 1 : Operators"
            on_release:
                app.root.current = "op"
                root.manager.transition.direction = "left"
        Button:
            text: "Lesson 2 : Loops"
            on_release:
                on_release: root.btn1()
        Button:
            text: "Lesson 3 : Data Structures"
            on_release:
                on_release: root.btn2()
        Button:
            text: "Lesson 4 : Functions"
            on_release:
                on_release: root.btn3()
        Button:
            text: "Lesson 5 :Data Handling-Files"
            on_release: root.btn4()
        Button:
            text: "Lesson 6 : Application of what was taught in the course."
            on_release: root.btn5()
<OperatorWindow>:
    name: "op"
    GridLayout:

        rows : 4

        Button:
            text : "||SOME BASICS OF PYTHON||\n\nCLICK to Learn"
            on_release :
                app.root.current = "basic"
                root.manager.transition.direction= "up"
        Label:
            text: "In this Lesson we will learn about Operators in Python"
            font_size : 20
        Label:
            text:"Operators are of the following types:\n1.Arithmetic Operators\n2.Comparison Opertaors\n3.Logical Operators\n4.Bitwise Operators\n5.Assignment Operators\n6.Identity Operators"
            font_size: 17
        FloatLayout:
            cols:2
            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 0.5, 0.65
                text:"Back"
                on_release :
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

            Button:
                pos_hint: {"x":0.5,"y":0}
                size_hint : 0.5,0.65
                text: "What are arithmetic Operators?"
                on_release:
                    app.root.current = "aop"
                    root.manager.transition.direction = "left"
<BasicWindow>
    name : "basic"
    FloatLayout :
        size: root.width, root.height
        rows: 3
        Label:
            size_hint : 1,0.04
            pos_hint : {"x":0,"y":0.92}
            font_size : 24
            text: "About Python "
        Label:
            size_hint: 1, 0.88
            pos_hint: {"x":0, "y":0.15}
            font_size: 18
            text :"\n\n\n\nPython is an easy to Learn language.\n\nIt is developer-friendly and high level programming language.\n\nPython is an interpreted language i.e. interpreter executes the code line by line at a time. \n\nThis makes debugging easy and thus suitable for beginners.\n\nPython supports object oriented language and concepts of classes and objects\n come into existence which will be further discussed.\n\nPython has a large standard library which provides rich set of module and functions \nso you do not have to write your own code for every single thing.\n\nPython is dynamically-typed language.\n That means the type (for example- int, double, long etc) for a variable is decided at run time\n not in advance. Because of this feature we do not need to specify the type of variable.\n "
        FloatLayout:
            cols : 2
            Button :
                pos_hint:{"x":0,"y":0}
                size_hint: 0.5, 0.14
                text : "Back to Content!"
                on_release :
                    app.root.current = "content"
                    root.manager.transition.direction = "right"
            Button :
                pos_hint: {"x":0.5,"y":0}
                size_hint : 0.5,0.14
                text : "Some Common Terms:"
                on_release:
                    app.root.current = "basic2"
                    root.manager.transition.direction = "left"
<Basic2Window>
    name : "basic2"
    FloatLayout :
        size: root.width, root.height
        rows: 3
        Label:
            size_hint : 1,0.04
            pos_hint : {"x":0,"y":0.92}
            font_size : 24
            text: "Some Common Terms"
        Label:
            size_hint: 1, 0.88
            pos_hint: {"x":0, "y":0.15}
            font_size: 20
            text :"\nOperands:The values on which the operators act\n\nOperators:Elements which perform operation like addition,subtraction etc.\n\nExpression:A sequence containing operands and operators\n\nConstant:The  type of Variable which has a particular value throughout the code.\n\nVariable: The value of this data type can be modified as and when required.\n\nGlobal variable:The variable that are accesible everywhere in the program.\n\nLocal variable : Variables only accesible within that particular function or class.\n "
        FloatLayout:
            cols : 2
            Button :
                pos_hint:{"x":0,"y":0}
                size_hint: 0.5, 0.14
                text : "Back"
                on_release :
                    app.root.current = "basic"
                    root.manager.transition.direction = "right"
            Button :
                pos_hint: {"x":0.5,"y":0}
                size_hint : 0.5,0.14
                text : "Some Basic Syntax:"
                on_release:
                    app.root.current = "basic3"
                    root.manager.transition.direction = "left"

<Basic3Window>
    name : "basic3"
    FloatLayout :
        size: root.width, root.height
        rows: 3
        Label:
            size_hint : 1,0.04
            pos_hint : {"x":0,"y":0.92}
            font_size : 24
            text: "About Python "
        Label:
            size_hint: 1, 0.88
            pos_hint: {"x":0, "y":0.15}
            font_size: 18
            text :"\n "
        FloatLayout:
            cols : 2
            Button :
                pos_hint:{"x":0,"y":0}
                size_hint: 0.5, 0.14
                text : "Back!"
                on_release :
                    app.root.current = "basic2"
                    root.manager.transition.direction = "right"
            Button :
                pos_hint: {"x":0.5,"y":0}
                size_hint : 0.5,0.14
                text : "Arithmatic Operators!"
                on_release:
                    app.root.current = "aop"
                    root.manager.transition.direction = "left"

<ArithmaticOperatorWindow>:
    name : "aop"
    FloatLayout:
        size: root.width, root.height
        rows: 2
        Label:
            size_hint: 1,0.2
            pos_hint : {"x":0 ,"y":0.8}
            font_size : 22
            text : "Introduction To Arithmetic Operator's"
        Label:
            size_hint: 1, 0.5
            pos_hint: {"x":0, "y":0.39}
            font_size: 15
            text : "\nArithmetic operators are used to perform mathematical operations like addition, subtraction, multiplication etc.\n\nOperator        Meaning\n +           Add two perands\n-           Subtract two perands \n*          Multiply two perands\n/          Divide the left operand by the right operand. Results in float output.\n%           Modulus- Remainder of the division of the left operand by the right.\n//          Floor division- division that results into whole number rounded to the previous number in the number lne.\n**          Exponent- left operand raised to the power of the right\n\nSyntax of Arithmetic operators loop:\n variable or constant<arithmetic operator>variable or constant"
        FloatLayout :
            cols : 2

            Label:
                size_hint : 0.35,0.45
                pos_hint:{"x":0,"y":0.11}
                text : "Example:\nx=15; y=4\n print(x+y)\nOUTPUT:\n19"
            Label :
                size_hint : 0.35,0.45
                pos_hint:{"x":0.5,"y":0.11}
                text : "print(13+7)\nOUTPUT:\n20"

            FloatLayout:
                cols : 2
                Button :
                    pos_hint:{"x":0,"y":0}
                    size_hint: 0.5, 0.15
                    text : "Back"
                    on_release :
                        app.root.current = "op"
                        root.manager.transition.direction = "right"
                Button :
                    pos_hint: {"x":0.5,"y":0}
                    size_hint : 0.5,0.15
                    text : "What is Comparision Operators?"
                    on_release:
                        app.root.current = "cop"
                        root.manager.transition.direction = "left"
<ConditionalOperatorWindow>
    name : "cop"
    FloatLayout:
        size: root.width, root.height
        rows:3
        Label:
            size_hint : 1,0.4
            pos_hint: {"x":0,"y":0.7}
            text:"Introduction To Condition Operator's"
            font_size : 20
        Label :
            size_hint : 1,0.2
            pos_hint: {"x":0,"y":0.6}
            text : "Comparison operators are used to compare values. It either returns True or False according to the condition.\nOperator        Meaning\n >        Greater than - True if the left operand is greater than the right\n<        Less than - True if the left operand is less than the right\n==        Equal to – True if both the operands are equal.\n>=        Greater than or equal to - True if the left operand is greater than or equal to the right.\n><=       Less than or equal to - True if the left operand is less than or equal to the right\n"
        Label :
            size_hint : 1,0.1
            pos_hint: {"x":0,"y":0.5}
            text : "Syntax of Comparison operators:\n (variable or constant<comparison operator>variable or constant)"
        FloatLayout:
            cols:2
            Label:
                size_hint : 0.35,0.45
                pos_hint:{"x":0,"y":0.15}
                text : "Example:\nx=15; y=4\n x>y\nOUTPUT:\nFalse\n"
                font_size : 15
            Label :
                size_hint : 0.35,0.45
                pos_hint:{"x":0.5,"y":0.15}
                text : "(x+y)>20\nOUTPUT:\nTrue (x//y)<=3\nOUTPUT:\nTrue"
                font_size : 15
            FloatLayout:
                cols : 2
                Button :
                    pos_hint:{"x":0,"y":0}
                    size_hint: 0.5, 0.15
                    text : "Back"
                    on_release :
                        app.root.current = "aop"
                        root.manager.transition.direction = "right"
                Button :
                    pos_hint: {"x":0.5,"y":0}
                    size_hint : 0.5,0.15
                    text : "What is Bitwise Operators?"
                    on_release:
                        app.root.current = "bop"
                        root.manager.transition.direction = "left"
<BitwiseOperatorWindow>
    name : "bop"
    FloatLayout:
        size: root.width, root.height
        rows:3
        Label:
            size_hint : 1,0.4
            pos_hint: {"x":0,"y":0.7}
            text:"Introduction To Bitwise Operator's"
            font_size : 20
        Label:
            size_hint : 1,0.2
            pos_hint: {"x":0,"y":0.6}
            text : "Bitwise operators act on operands as if they were string of binary digits. It operates bit by bit, hence the name.\n\nOperator        Meaning        \n&             Bitwise AND        x&y=0(0000 0000)\n|                Bitwise OR        x|y=14(0000 1110)\n~            Bitwise NOT        ~x=-11(1111 0101)\n^            Bitwise XOR        x^y=14(0000 1110)\n>>           Bitwise Right Shift        x>>2=2(0000 0010)\n<<           Bitwise Left Shift        x<<2=40(0010 1000)\n"
        Label:
            size_hint : 1,0.1
            pos_hint: {"x":0,"y":0.5}
            text : "Syntax of Bitwise operators varies with the kind of operator used as given above in the table"
        FloatLayout:
            cols:2
            Label:
                size_hint : 0.35,0.45
                pos_hint:{"x":0,"y":0.15}
                text : "Example:\nx=15; y=4\nx|y=4\nOUTPUT:\nTrue\n"
                font_size : 15
            Label :
                size_hint : 0.35,0.45
                pos_hint:{"x":0.5,"y":0.15}
                text : "x&y=15\nOUTPUT:\nFalse x^y=15\nOUTPUT:\nTrue"
                font_size : 15
            FloatLayout:
                cols : 2
                Button :
                    pos_hint:{"x":0,"y":0}
                    size_hint: 0.5, 0.15
                    text : "Back"
                    on_release :
                        app.root.current = "cop"
                        root.manager.transition.direction = "right"
                Button :
                    pos_hint: {"x":0.5,"y":0}
                    size_hint : 0.5,0.15
                    text : "What is Logical Operators?"
                    on_release:
                        app.root.current = "lop"
                        root.manager.transition.direction = "left"


<LogicalOperatorWindow>
    name: "lop"
    FloatLayout:
        size: root.width, root.height
        rows:3
        Label:
            size_hint : 1,0.4
            pos_hint: {"x":0,"y":0.7}
            text:"Introduction To Logical Operator's"
            font_size : 20
        Label:
            size_hint : 1,0.2
            pos_hint: {"x":0,"y":0.6}
            text : "Logical operators are used to compare values. It either returns True or False according to the condition.\nOperator        Meaning\n >        Greater than - True if the left operand is greater than the right\n<        Less than - True if the left operand is less than the right\n==        Equal to – True if both the operands are equal.\n>=        Greater than or equal to - True if the left operand is greater than or equal to the right.\n><=       Less than or equal to - True if the left operand is less than or equal to the right\n"
        Label:
            size_hint : 1,0.1
            pos_hint: {"x":0,"y":0.5}
            text : "Syntax of Comparison operators:\n (variable or constant<comparison operator>variable or constant. "
        FloatLayout:
            cols:2
            Label:
                size_hint : 0.35,0.45
                pos_hint:{"x":0,"y":0.15}
                text : "Example:\nx=15; y=4\n x>y\nOUTPUT:\nFalse\n"
                font_size : 15
            Label :
                size_hint : 0.35,0.45
                pos_hint:{"x":0.5,"y":0.15}
                text : "n(x+y)>20\nOUTPUT:\nTrue (x//y)<=3\nOUTPUT:\nTrue"
                font_size : 15
            FloatLayout:
                cols : 2
                Button :
                    pos_hint:{"x":0,"y":0}
                    size_hint: 0.5, 0.15
                    text : "Back"
                    on_release :
                        app.root.current = "bop"
                        root.manager.transition.direction = "right"
                Button :
                    pos_hint: {"x":0.5,"y":0}
                    size_hint : 0.5,0.15
                    text : "What is Assignment Operator?"
                    on_release:
                        app.root.current = "asop"
                        root.manager.transition.direction = "left"

<AssignmentOperatorWindow>
    name: "asop"
    FloatLayout:
        size: root.width, root.height
        rows:3
        Label:
            size_hint : 1,0.4
            pos_hint: {"x":0,"y":0.7}
            text:"Introduction To Assignment Operator's"
            font_size : 20
        Label:
            size_hint : 1,0.2
            pos_hint: {"x":0,"y":0.6}
            text : "Assignment operators are used in Python to assign values to variables.\n"
        Label:
            size_hint : 1,0.1
            pos_hint: {"x":0,"y":0.5}
            text : "Syntax of Assignment operators:\n (variable)<assignment operator>variable or constant. "
        FloatLayout:
            cols:2
            Label:
                size_hint : 0.35,0.45
                pos_hint:{"x":0,"y":0.15}
                text : "Example:\nx=15; y=4\n x>y\nOUTPUT:\nFalse\n"
                font_size : 15
            Label :
                size_hint : 0.35,0.45
                pos_hint:{"x":0.5,"y":0.15}
                text : "n(x+y)>20\nOUTPUT:\nTrue (x//y)<=3\nOUTPUT:\nTrue"
                font_size : 15
            FloatLayout:
                cols : 2
                Button :
                    pos_hint:{"x":0,"y":0}
                    size_hint: 0.5, 0.15
                    text : "Back"
                    on_release :
                        app.root.current = "lop"
                        root.manager.transition.direction = "right"
				Button :
                    pos_hint: {"x":0.5,"y":0}
                    size_hint : 0.5,0.15
                    text : "What is Identity Operators?"
                    on_release:
                        app.root.current = "iop"
                        root.manager.transition.direction = "left"


<IdentityOperatorWindow>
    name: "iop"
    FloatLayout:
        size: root.width, root.height
        rows:3
        Label:
            size_hint : 1,0.4
            pos_hint: {"x":0,"y":0.7}
            text:"Introduction To Identity Operator's"
            font_size : 23
        Label:
            size_hint : 1,0.2
            pos_hint: {"x":0,"y":0.6}
            text : "'is' and 'is not' are the identity operators in Python.\n They are used to check if two values (or variables) are located on the same part of the memory.\n Two variables that are equal does not imply that they are identical.\n"
        Label:
            size_hint : 1,0.1
            pos_hint: {"x":0,"y":0.5}
            text : "Syntax of Identity operators:\n (variable)<Identity  operator>variable or constant. "
        FloatLayout:
            cols:2
            Label:
                size_hint : 0.35,0.45
                pos_hint:{"x":0,"y":0.15}
                text : "Example:\nx=15; y=4\n  is >y\nOUTPUT:\nFalse\n"
                font_size : 15
            Label :
                size_hint : 0.35,0.45
                pos_hint:{"x":0.5,"y":0.15}
                text : "\nx+y is 20\nOUTPUT:\nTrue x is not y\nOUTPUT:\nTrue"
                font_size : 15
            FloatLayout:
                cols : 2
                Button :
                    pos_hint:{"x":0,"y":0}
                    size_hint: 0.5, 0.15
                    text : "Back"
                    on_release :
                        app.root.current = "asop"
                        root.manager.transition.direction = "right"
                Button :
                    pos_hint: {"x":0.5,"y":0}
                    size_hint : 0.5,0.15
                    text : "Let's take a TEST!!!"
                    on_release:
                        on_release : root.select()
                        root.manager.transition.direction = "left"

<Test1Window>:
    name: "test1"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "\n\n||Write the correct option you think press enter and go to next question||\n\n\nQ. Which is the correct operator for power(xy)?\na) X^y\nb) X**y\nc) X^^y\nd) None of the mentioned\n\n"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "test2"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test2Window>:
    name: "test2"

    answer : answer
    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "Q. Which one of these is floor division?\na) /\nb) //\nc) %\nd) None of the mentioned\n\n"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "test3"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :

                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test3Window>:
    name: "test3"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "\n\nQ.What is the order of precedence in python?\ni) Parentheses\nii) Exponential\niii) Multiplication\niv) Division\nv) Addition\nvi) Subtraction\n\n\na) i,ii,iii,iv,v,vi\nb) ii,i,iii,iv,v,vi\nc) ii,i,iv,iii,v,vi\nd) i,ii,iii,iv,vi,v\n\n"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "test4"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :

                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test4Window>:
    name: "test4"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "Q.What is the answer to this expression, 22 % 3 is?\na) 7\nb) 1\nc) 0\nd) 5\n\n"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "test5"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test5Window>:
    name: "test5"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "Q.Mathematical operations can be performed on a string.\na) True\nb) False\nc)May be or maybe not \nd)Sometimes\n\n"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "fifth"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test11Window>:
    name: "test11"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "\n\n\n\n\n\nQ. What is the output of the following assignment operator-\n\n        y = 10\n        x = y += 2\n        print(x)\n\na)  2\nb)  10\nc)  12 \nd)  Syntax Error\n\n\n"
            font_size: 20
        TextInput :
            pos_hint:{"x":0.25,"y":0.35}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "test22"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test22Window>:
    name: "test22"

    answer : answer
    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "\n\n\nQ. What is the output of print(10 - 4 * 2) :-\n\n\na)  2\nb)  10\nc)  12 \nd)  Syntax Error\n\n\n"
            font_size: 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "test33"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test33Window>:
    name: "test33"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "\n\n\n\n\nQ. What is the output of the following Python code-\nx = 10\ny = 50\nif (x ** 2 > 100 and y < 100):\n      print(x, y)\n\na) 100 500 \nb) 10 50 \nc) 100 50 \nd)  None\n\n\n"
            font_size: 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.35}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "test44"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test44Window>:
    name: "test44"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "\n\n\n\n\nQ. What is the output of the following code-\n\nx = 100\ny = 50\nprint(x and y)\n\na)  True\nb)  100\nc)  50 \nd)  False\n\n\n"
            font_size : 19
        TextInput :
            pos_hint:{"x":0.25,"y":0.35}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "test55"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test55Window>:
    name: "test55"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "\n\n\n\n\n\nQ. What is the output of the following code-\n  x = 6\n  y = 2\n  print(x ** y)\n  print(x // y)\n\n  a) 66\n       0\n  b) 36\n       0\n  c)66\n       3\n  d) 36\n       3\n"
            font_size: 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.30}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "fifth"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test111Window>:
    name: "test111"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "\n\n\n\nQ. What is the value of the following Python Expression\n\nprint(36 / 4)\n\na)0.9\nb) 9.0\nc) 36/4\nd) 9"
            font_size: 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.35}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "test222"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test222Window>:
    name: "test222"

    answer : answer
    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "\n\n\nQ. What is the output of the following addition (+) operator\n\na = [10, 20]\nb = a\nb += [30, 40]\nprint(a)\nprint(b)\n\na) [10, 20, 30, 40]\n     [10, 20, 30, 40] \nb) [10, 20]\n     [10, 20, 30, 40] "
            font_size : 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.35}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "test333"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test333Window>:
    name: "test333"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "\n\n\n\n\nQ. 4 is 100 in binary and 11 is 1011. What is the output of the following bitwise operators?\n\na = 4\nb = 11\nprint(a | b)\nprint(a >> 2)\n\na) 15\n     1\n\nb)14\n    1"
            font_size : 17
        TextInput :
            pos_hint:{"x":0.15,"y":0.35}
            size_hint: 0.75,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "test444"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test444Window>:
    name: "test444"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "\n\n\nQ.Which of the following operators has the highest precedence?\na) not\nb) and\nc) *\nd) +\n\n"
            font_size: 22
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "test555"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test555Window>:
    name: "test555"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "Q. What is the output of the following code-\n\nprint(bool(0), bool(3.14159), bool(-3), bool(1.0+1j))\n\na) True True False True \nb) False True True True \nc) True True False True \nd)False True False True"
            font_size: 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "fifth"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<FifthWindow>:
    name: "fifth"

    Button:
        text: "BACK TO CONTENTS"
        font_size : 30
        on_release:
            app.root.current = "content"
            root.manager.transition.direction = "left"

<LoopWindow>:

    name: "loop"
    GridLayout:

        rows : 3
        Label:
            text: "In this Lesson we will learn about Loops in Python"
            font_size : 20
        Label:
            text:"Loops are statements which are \nused to execute a particular statement or set of statements repeatedly withuout \nhaving to write them again and again."
            font_size: 17
        FloatLayout:
            cols:2
            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 0.5, 0.65
                text:"Back"
                on_release :
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

            Button:
                pos_hint: {"x":0.5,"y":0}
                size_hint : 0.5,0.65
                text: "for loop"
                on_release:
                    app.root.current = "FL"
                    root.manager.transition.direction = "left"

<Forloop>
	name:"FL"
	GridLayout:
		size: root.width, root.height
		rows: 3
		Label:
			text:"\nIn this lesson we will learn about for loops.\n\n for in loops are used to run a set of task for a certain number of times.\n These loops iterate over any sequences such as items in an array,range,list, \ntuples or characters in a string.\n We use this loop to do some \nrepetitive processes for a fixed amount of times.\n\n"
			font_size: 19
		Label:
			text:"Syntax: \nfor val in  sequence:\n      Body of for\n Here val is the \n variable that takes the value of the item in the given sequence on each\n iteration.The loop terminates when e reach the last item in the sequence\n\n Example:\n Problem statement - To print Hello world 100 times. \n Solution:\n\n for i in (100)\n        print(""Hello world"")"
		FloatLayout:
			cols: 2
			Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 0.5, 0.65
                text:"Back"
                font_size: 17
                on_release :
                    app.root.current = "loop"
                    root.manager.transition.direction = "right"

            Button:
                pos_hint: {"x":0.5,"y":0}
                size_hint : 0.5,0.65
                text: "for with else"
                on_release:
                    app.root.current = "FWE"
                    root.manager.transition.direction = "left"

<Forwithelse>
	name: "FWE"
	GridLayout:
		size: root.width,root.height
		rows: 3
		Label:
			text: "\nThis lesson is about using else statement in with the for loop. A for loop can\n have an optional 'else' block as well. The 'else' part is executed if the terms\n in the sequence used in for loop exhaust.The break keyword can also be used \nto terminate the for loop.In such cases, the else part is ignored.The else \npart of the for loop works if break does not occur.\n\n"
			font_size: 17
		Label:
			text: " Example:/ndigits=[0,1,5]\nfor i in digits:\n    print(i)\nelse:\n    print(""No items Left"")\n\nOutput:\n0n\1\n5\nNo items Left"
		FloatLayout:
			cols: 2
			Button:
				pos_hint:{"x":0,"y":0}
                size_hint: 0.5, 0.65
                text:"Back"
                font_size: 17
                on_release :
                    app.root.current = "FL"
                    root.manager.transition.direction = "right"
            Button:
            	pos_hint: {"x":0.5,"y":0}
                size_hint : 0.5,0.65
                text: "While loop"
                on_release:
                    app.root.current = "While"
                    root.manager.transition.direction = "left"

<WhileLoop>
	name: "While"
	FloatLayout:
		size: root.width,root.height
		rows: 3
		Label:
			pos_hint:{"x":0,"y":0.45}
            size_hint: 1, 0.65
			text: " In this module. We will learn about another kind of loop used in Python - \n'The while loop'.The while loop in python is used to iterate over a block of \ncode as long as the test expression(condition) is true. This loop is mostly \npreferred when we don't know the number of times to iterate beforehand.\n\nIn the whilel loop, the test expression is validated before entering the body of the loop.\n The body of the loop is entered only if the test_expression evaluates to 'True'.\n After one iteration, the test expression is validated again.\nThis process continues until the test_expression evaluatesto 'False'\n\n"
			font_size: 17
		Label:
			pos_hint:{"x":0,"y":0.10}
            size_hint: 1, 0.5
			font_size: 17
			text: " Example:\nn,sum=10,0\nwhile(n>0):\n    sum+=n\n    n-=1\nprint(sum)\n OUTPUT:55.\n\n Syntax:\n while(test_expression):\n    Body of while\n\n"
		FloatLayout:
			cols: 2
			Button:
				pos_hint:{"x":0,"y":0}
                size_hint: 0.5, 0.15
                text:"Back"
                font_size: 17
                on_release :
                    app.root.current = "FWE"
                    root.manager.transition.direction = "right"
            Button:
            	pos_hint: {"x":0.5,"y":0}
                size_hint : 0.5,0.15
                text: "While with else"
                on_release:
                    app.root.current = "WWE"
                    root.manager.transition.direction = "left"

<WhileWithElse>
	name:"WWE"
	GridLayout:
		size: root.width,root.height
		rows: 3
		Label:
			text: "The implementation of else block in while similar to the for loop. \nIf the condition in the while block evaluates to false, then the else part gets executed."
		Label:
			text:"Example:\n i=0\nwhile(i<3);\n    print(i)\n    i+=1\nelse:\n    Print(1111)\nOUTPUT:\n0\n1\n2\n1111"
		FloatLayout:
			cols: 2
			Button:
				pos_hint:{"x":0,"y":0}
                size_hint: 0.5, 0.65
                text:"Back"
                font_size: 17
                on_release :
                    app.root.current = "While"
                    root.manager.transition.direction = "right"
            Button:
            	pos_hint: {"x":0.5,"y":0}
                size_hint : 0.5,0.65
                text: "If....Else"
                on_release:
                    app.root.current = "ifelse"
                    root.manager.transition.direction = "left"

<IfElse>
	name: "ifelse"
	GridLayout:
		size: root.height,root.width
		rows: 3
		Label:
			text: "The If....Else block in python is a conditional loop. The program enters inside the\n if block only when the condition specified in the if statement is True, Otherwise,\n the else part is executed. The If.....Else loop can be used to verify conditions\n as well as to iterate over a block of statements."
		    font_size: 18
		Label:
			text:"Example:\n i=0\nif(i==0)\n    print(i)\nelse:\n\nThe point to be noted here is that even if the condition\n in the if statement is True,\n the if block will not be executed as the else block is empty.\n If can be alone used without else but else cannot be used without if."
		    font_size: 18
		FloatLayout:
			cols: 2
			Button:
				pos_hint:{"x":0,"y":0}
                size_hint: 0.5, 0.65
                text:"Back"
                font_size: 17
                on_release :
                    app.root.current = "WWE"
                    root.manager.transition.direction = "right"
            Button:
            	pos_hint: {"x":0.5,"y":0}
                size_hint : 0.5,0.65
                text: "Try Except"
                on_release:
                    app.root.current = "TC"
                    root.manager.transition.direction = "left"

<TryCatch>
	name: "TC"
	GridLayout:
		size: root.height,root.width
		rows: 3
		Label:
			text: "The try...except...finally block is another block of statements\n used to control the flow of the program.\n The try statement contains the block of statements for validation.\n If the try statement returns True,\n then the statements within the try block are executed otherwise,\n all the other cases are executed in the except block.\nThe except block or finally block is executed which includes the output to be shown.\n The except block and finally block can be used independent of each other."
		    font_size: 17
		Label:
			text:"Example:\n try:\n    f=open(<filename with type>,encoding-'utf-8')\nfinally:\n    f.close\n\n This type of constructor makes sure that the file is executed\n even if the exception occurs during the program execution."
		    font_size: 19
		FloatLayout:
			cols: 2
			Button:
				pos_hint:{"x":0,"y":0}
                size_hint: 0.5, 0.65
                text:"Back"
                font_size: 17
                on_release :
                    app.root.current = "WWE"
                    root.manager.transition.direction = "right"
            Button:
            	pos_hint: {"x":0.5,"y":0}
                size_hint : 0.5,0.65
                text: "Let's take a test"
                on_release:
                    app.root.current = "2final"
                    root.manager.transition.direction = "left"




<DataWindow>
    name: "data"

    Button :
        text: "lesson 3"
        font_size : 30
        on_release:
            app.root.current = "final3"
            root.manager.transition.direction = "left"

<FunctionWindow>:

    name: "function"

    Button :
        text: "lesson 4"
        font_size : 30
        on_release:
            app.root.current = "final4"
            root.manager.transition.direction = "left"

<DataHandlingWindow>:

    name: "datahandling"

    Button :
        text: "lesson 5"
        font_size : 30
        on_release:
            app.root.current = "final5"
            root.manager.transition.direction = "left"

<AppWindow>:

    name: "app"

    Button :
        text: "lesson 6"
        font_size : 30
        on_release:
            app.root.current = "final6"
            root.manager.transition.direction = "left"

<tFinalWindow>:
    name: "2final"
    Button :
        text : "PRESS TO START TEST"
        font_size : 30
        on_release:
            on_release : root.select()
            root.manager.transition.direction = "left"

<FinalWindow3>:
    name: "final3"
    Button :
        text : "Let's take a TEST!!!"
        font_size : 30
        on_release:
            on_release : root.select()
            root.manager.transition.direction = "left"


<FinalWindow4>:
    name: "final4"
    Button :
        text : "Let's take a TEST!!!"
        font_size : 30
        on_release:
            on_release : root.select()
            root.manager.transition.direction = "left"
<FinalWindow5>:
    name: "final5"
    Button :
        text : "Let's take a TEST!!!"
        font_size : 30
        on_release:
            on_release : root.select()
            root.manager.transition.direction = "left"

<FinalWindow6>:
    name: "final6"
    Button :
        text : "Test Yourself!!!"
        font_size : 30
        on_release:
            on_release : root.select()
            root.manager.transition.direction = "left"
<tTest1Window>:
    name: "2test1"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "2.1"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "2test2"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<tTest2Window>:
    name: "2test2"

    answer : answer
    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "2.2"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "2test3"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<tTest3Window>:
    name: "2test3"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "2.3"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "2test4"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<tTest4Window>:
    name: "2test4"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "2.4"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "2test5"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<tTest5Window>:
    name: "2test5"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "2.5"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "fifth"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<tTest11Window>:
    name: "2test11"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "2.11"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "2test22"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<tTest22Window>:
    name: "2test22"

    answer : answer
    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "2.22"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "2test33"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<tTest33Window>:
    name: "2test33"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "2.33"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "2test44"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<tTest44Window>:
    name: "2test44"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "2.44"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "2test55"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<tTest55Window>:
    name: "2test55"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "2.55"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "fifth"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<tTest111Window>:
    name: "2test111"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "2.111"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "2test222"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<tTest222Window>:
    name: "2test222"

    answer : answer
    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "2.222"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "2test333"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<tTest333Window>:
    name: "2test333"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "2.333"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "2test444"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<tTest444Window>:
    name: "2test444"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "2.444"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "2test555"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<tTest555Window>:
    name: "2test555"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "2.555"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "fifth"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test1Window3>:
    name: "3test1"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "3.1"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "3test2"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test2Window3>:
    name: "3test2"

    answer : answer
    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "3.2"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "3test3"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test3Window3>:
    name: "3test3"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "3.3"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "3test4"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test4Window3>:
    name: "3test4"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "3.4"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "3test5"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test5Window3>:
    name: "3test5"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "3.5"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "fifth"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test11Window3>:
    name: "3test11"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "3.11"
            font_size: 20
        TextInput :
            pos_hint:{"x":0.25,"y":0.35}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "3test22"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test22Window3>:
    name: "3test22"

    answer : answer
    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "3.22"
            font_size: 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "3test33"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test33Window3>:
    name: "3test33"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "\n\n\n\n\nQ. What is the output of the following Python code-\nx = 10\ny = 50\nif (x ** 2 > 100 and y < 100):\n      print(x, y)\n\na) 100 500 \nb) 10 50 \nc) 100 50 \nd)  None\n\n\n"
            font_size: 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.35}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "3test44"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test44Window3>:
    name: "3test44"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "\n\n\n\n\nQ. What is the output of the following code-\n\nx = 100\ny = 50\nprint(x and y)\n\na)  True\nb)  100\nc)  50 \nd)  False\n\n\n"
            font_size : 19
        TextInput :
            pos_hint:{"x":0.25,"y":0.35}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "3test55"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test55Window3>:
    name: "3test55"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "\n\n\n\n\n\nQ. What is the output of the following code-\n  x = 6\n  y = 2\n  print(x ** y)\n  print(x // y)\n\n  a) 66\n       0\n  b) 36\n       0\n  c)66\n       3\n  d) 36\n       3\n"
            font_size: 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.30}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "fifth"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test111Window3>:
    name: "3test111"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "3.111"
            font_size: 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.35}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "3test222"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test222Window3>:
    name: "3test222"

    answer : answer
    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "\n\n\nQ. What is the output of the following addition (+) operator\n\na = [10, 20]\nb = a\nb += [30, 40]\nprint(a)\nprint(b)\n\na) [10, 20, 30, 40]\n     [10, 20, 30, 40] \nb) [10, 20]\n     [10, 20, 30, 40] "
            font_size : 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.35}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "3test333"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test333Window3>:
    name: "3test333"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "\n\n\n\n\nQ. 4 is 100 in binary and 11 is 1011. What is the output of the following bitwise operators?\n\na = 4\nb = 11\nprint(a | b)\nprint(a >> 2)\n\na) 15\n     1\n\nb)14\n    1"
            font_size : 17
        TextInput :
            pos_hint:{"x":0.15,"y":0.35}
            size_hint: 0.75,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "3test444"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test444Window3>:
    name: "3test444"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "\n\n\nQ.Which of the following operators has the highest precedence?\na) not\nb) and\nc) *\nd) +\n\n"
            font_size: 22
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "3test555"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test555Window3>:
    name: "3test555"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "Q. What is the output of the following code-\n\nprint(bool(0), bool(3.14159), bool(-3), bool(1.0+1j))\n\na) True True False True \nb) False True True True \nc) True True False True \nd)False True False True"
            font_size: 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "fifth"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test1Window4>:
    name: "4test1"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "4.1"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "4test2"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test2Window4>:
    name: "4test2"

    answer : answer
    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "4.2"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "4test3"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test3Window4>:
    name: "4test3"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "4.3"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "4test4"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test4Window4>:
    name: "4test4"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "4.4"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "4test5"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test5Window4>:
    name: "4test5"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "4.5"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "fifth"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test11Window4>:
    name: "4test11"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "4.11"
            font_size: 20
        TextInput :
            pos_hint:{"x":0.25,"y":0.35}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "4test22"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test22Window4>:
    name: "4test22"

    answer : answer
    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "4.22"
            font_size: 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "4test33"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test33Window4>:
    name: "4test33"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "4.33"
            font_size: 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.35}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "4test44"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test44Window4>:
    name: "4test44"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "4.44"
            font_size : 19
        TextInput :
            pos_hint:{"x":0.25,"y":0.35}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "4test55"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test55Window4>:
    name: "4test55"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "4.55"
            font_size: 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.30}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "fifth"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test111Window4>:
    name: "4test111"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "4.111"
            font_size: 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.35}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "4test222"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test222Window4>:
    name: "4test222"

    answer : answer
    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "\4.222"
            font_size : 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.35}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "4test333"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test333Window4>:
    name: "4test333"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "4.333"
            font_size : 17
        TextInput :
            pos_hint:{"x":0.15,"y":0.35}
            size_hint: 0.75,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "4test444"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test444Window4>:
    name: "4test444"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "4.444"
            font_size: 22
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "4test555"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test555Window4>:
    name: "4test555"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "4.555"
            font_size: 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "fifth"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test1Window5>:
    name: "5test1"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "5.1"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "5test2"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test2Window5>:
    name: "5test2"

    answer : answer
    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "5.2"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "5test3"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test3Window5>:
    name: "5test3"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "5.3"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "5test4"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test4Window5>:
    name: "5test4"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "5.4"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "5test5"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test5Window5>:
    name: "5test5"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "5.5"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "fifth"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test11Window5>:
    name: "5test11"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "5.11"
            font_size: 20
        TextInput :
            pos_hint:{"x":0.25,"y":0.35}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "5test22"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test22Window5>:
    name: "5test22"

    answer : answer
    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "5.22"
            font_size: 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "5test33"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test33Window5>:
    name: "5test33"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "5.33"
            font_size: 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.35}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "5test44"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test44Window5>:
    name: "5test44"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "5.44"
            font_size : 19
        TextInput :
            pos_hint:{"x":0.25,"y":0.35}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "5test55"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test55Window5>:
    name: "5test55"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "5.55"
            font_size: 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.30}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "fifth"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test111Window5>:
    name: "5test111"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "5.111"
            font_size: 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.35}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "5test222"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test222Window5>:
    name: "5test222"

    answer : answer
    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "5.222"
            font_size : 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.35}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "5test333"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test333Window5>:
    name: "5test333"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "5.333"
            font_size : 17
        TextInput :
            pos_hint:{"x":0.15,"y":0.35}
            size_hint: 0.75,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "5test444"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test444Window5>:
    name: "5test444"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "5.444"
            font_size: 22
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "5test555"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test555Window5>:
    name: "5test555"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "5.555"
            font_size: 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "fifth"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test1Window6>:
    name: "6test1"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "6.1"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "6test2"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test2Window6>:
    name: "6test2"

    answer : answer
    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "6.2"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "6test3"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test3Window6>:
    name: "6test3"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "6.3"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "6test4"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test4Window6>:
    name: "6test4"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "4.4"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "6test5"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test5Window6>:
    name: "6test5"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "6.5"
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "fifth"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test11Window6>:
    name: "6test11"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "6.11"
            font_size: 20
        TextInput :
            pos_hint:{"x":0.25,"y":0.35}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "6test22"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test22Window6>:
    name: "6test22"

    answer : answer
    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "6.22"
            font_size: 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "6test33"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test33Window6>:
    name: "6test33"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "6.33"
            font_size: 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.35}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "6test44"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<Test44Window6>:
    name: "6test44"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "6.44"
            font_size : 19
        TextInput :
            pos_hint:{"x":0.25,"y":0.35}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "6test55"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test55Window6>:
    name: "6test55"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "6.55"
            font_size: 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.30}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "fifth"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test111Window6>:
    name: "6test111"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "6.111"
            font_size: 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.35}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "6test222"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test222Window6>:
    name: "6test222"

    answer : answer
    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "6.222"
            font_size : 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.35}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "6test333"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test333Window6>:
    name: "6test333"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "6.333"
            font_size : 17
        TextInput :
            pos_hint:{"x":0.15,"y":0.35}
            size_hint: 0.75,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "6test444"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test444Window6>:
    name: "6test444"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "6.444"
            font_size: 22
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "6test555"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"


<Test555Window6>:
    name: "6test555"

    answer : answer

    FloatLayout:
        size : root.height, root.width
        rows:3
        Label:
            pos_hint:{"x":0,"y":0.65}
            size_hint: 1, 0.25
            text : "6.555"
            font_size: 18
        TextInput :
            pos_hint:{"x":0.25,"y":0.45}
            size_hint: 0.55,0.10
            id : answer
            multiline : False
        FloatLayout:
            rows : 2

            Button :
                pos_hint: {"x":0,"y":0.1}
                size_hint : 1,0.15
                text : "NEXT"
                on_release:
                    root.get_text_inputs()
                    app.root.current = "fifth"
                    root.manager.transition.direction = "left"


            Button:
                pos_hint:{"x":0,"y":0}
                size_hint: 1, 0.1
                text: "Cancel Test Move out"
                on_release :
                    root.zero()
                    app.root.current = "content"
                    root.manager.transition.direction = "right"

<App2Window>

    name: "app2"

    FloatLayout:
        rows: 3
        size : root.height, root.width
        FloatLayout:
            cols: 2
            Label:
                pos_hint:{"x":0,"y":0.8}
                size_hint: 0.1, 0.20
                text : "   "
                font_size: 65
            Label:
                pos_hint:{"x":0.000000001,"y":0.78}
                size_hint: 1, 0.20
                text : "Python Learning----------------------------------------------------------------------------------"
                font_size: 25
        Label:
            pos_hint:{"x":0,"y":0.25}
            size_hint: 1, 0.50
            text : "So, this far we have learnt a few of the many properties and concepts of Python\nsome of them are:-\n      1) Basic syntax\n\n       2) Usage of Loops\n\n       3) Various data  structures\n\n       4) About If/Else conditions\n\n       5) Functions\n\nMuch more..."
            font_size: 21
        Button:
            pos_hint:{"x":0,"y":0}
            size_hint: 1, 0.20
            text : "Now, Let's see if we can Apply these concepts to develop Executable Programs..."
            font_size: 19
            on_release:
                app.root.current = "final6"
                root.manager.transition.direction = "left"



